[package]
name = "kabu-storage-db"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
bb8.workspace = true
diesel.workspace = true
diesel-async.workspace = true
diesel_migrations = { version = "2.2", features = ["postgres"] }
thiserror.workspace = true
tracing.workspace = true
