[package]
name = "kabu-rpc-state"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
kabu-core-blockchain.workspace = true
kabu-storage-db.workspace = true
kabu-types-blockchain.workspace = true
revm.workspace = true
