[package]
name = "keys"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
kabu-types-entities.workspace = true

aes-gcm.workspace = true
clap.workspace = true
eyre.workspace = true
hex.workspace = true
pbkdf2.workspace = true
rand.workspace = true
sha2.workspace = true
