[package]
name = "kabu-types-entities"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
kabu-defi-address-book.workspace = true
kabu-evm-db.workspace = true
kabu-evm-utils.workspace = true
kabu-node-debug-provider.workspace = true
kabu-types-blockchain.workspace = true
kabu-types-market.workspace = true

aes.workspace = true
eyre.workspace = true
hex.workspace = true
indexmap.workspace = true
lazy_static.workspace = true
rand.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true

alloy-consensus.workspace = true
alloy-json-rpc.workspace = true
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types.workspace = true
alloy-signer-local.workspace = true


[build-dependencies]
hex.workspace = true
rand.workspace = true

[dev-dependencies]
alloy-node-bindings.workspace = true
alloy-rpc-client.workspace = true
criterion = { version = "0.5.1", features = ["async_tokio"] }

[[bench]]
harness = false
name = "benchmark"
