[package]
name = "kabu-types-market"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
kabu-defi-address-book.workspace = true
kabu-evm-db.workspace = true
kabu-node-debug-provider.workspace = true
kabu-types-blockchain.workspace = true

eyre.workspace = true
serde.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true

alloy-evm.workspace = true
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-types-trace.workspace = true
alloy-sol-types.workspace = true

revm.workspace = true

[dev-dependencies]
serde_json.workspace = true
