[package]
name = "kabu-core-router"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
kabu-core-components.workspace = true
kabu-types-entities.workspace = true
kabu-types-events.workspace = true

eyre.workspace = true
tokio.workspace = true
tracing.workspace = true

revm.workspace = true

# reth
reth-ethereum-primitives.workspace = true
reth-node-types.workspace = true
reth-tasks.workspace = true
