[package]
name = "kabu-types-blockchain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
kabu-node-debug-provider.workspace = true

chrono.workspace = true
eyre.workspace = true
lazy_static.workspace = true
tokio.workspace = true
tracing.workspace = true

# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-rpc-types-trace.workspace = true


op-alloy.workspace = true

[dev-dependencies]
dotenvy.workspace = true
env_logger.workspace = true
serde_json.workspace = true
url.workspace = true

alloy-rpc-client.workspace = true
