[package]
name = "kabu-types-events"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
kabu-types-blockchain.workspace = true
kabu-types-entities.workspace = true
kabu-types-market.workspace = true
kabu-types-swap.workspace = true

alloy-consensus.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types.workspace = true
revm.workspace = true

# reth
reth-ethereum-primitives.workspace = true
reth-node-types.workspace = true

chrono.workspace = true
eyre.workspace = true
